# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: ZackadDev
author: zackad
email: zackad.dev@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I'm a simple man. I do what I want and what I could. Otherwise
  it's a trial and error.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blog.zackad.com" # the base hostname & protocol for your site, e.g. http://example.com
github_username: zackad

# Sosial media
social:
  email: zackad [dot] dev [at] gmail [dot] com
  github:
    username: zackad
    url: https://github.com/zackad
  gitlab:
    username: zackad
    url: https://gitlab.com/zackad
  stackoverflow:
    username: zackad
    url: https://stackoverflow.com/users/6265296/zackad
  youtube:
    username: ZackadDev
    url: https://www.youtube.com/channel/UCao_VdbgaSy2CnB0VdySOEQ

# Third party services
disqus:
  shortname: zackadtech
google_analytics: UA-105186998-1

# Build settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      category: "en"
      author: "zackad"
future: true
markdown: kramdown
plugins_dir:
  - jekyll-feed
  - jekyll-archives
  - jekyll-tidy
  - jekyll-sitemap
  - ./_plugins
exclude:
  # Exclude directories
  - js
  - node_modules
  # Exclude files
  - LICENSE
  - README.md
  - Gemfile
  - Gemfile.lock
  - deploy_rsa.enc
  - package.json
  - package-lock.json
  - webpack.config.js
sass:
  style: compressed

# jekyll archives plugin
jekyll-archives:
  enabled:
    - year
    - month
    - tags
  layouts:
    year: archive-year
    month: archive-month
    tag: archive-tags
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/category/:name/'
